FROM node:13.12.0-alpine

WORKDIR /

ENV PATH node_modules/.bin:$PATH

COPY package.json .
COPY package-lock.json .
RUN npm install --silent

RUN npm install react-scripts -g --silent
RUN npm install bootstrap react-bootstrap --save

COPY . .
EXPOSE 3000
CMD ["npm", "start"]
